version: '3'

services:
  php-apache:
    build: ./includes
    volumes:
      - ./src/:/var/www/html
    ports:
      - 80:80

  mysql-server:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./db/:/var/lib/mysql
    ports:
      - 3306:3306

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
